modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ExpirationDates/issues"
license="MIT"

[[mods]]
modId="expirationdates"
version="${file.jarVersion}"
displayName="Expiration Dates"
displayURL="https://www.curseforge.com/minecraft/mc-mods/expiration-dates"
authors="Mrbysco"
credits="Nekomaster for the idea"
description='''
Allows you to set expiration dates on items
'''
[[dependencies.expirationdates]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.expirationdates]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="expirationdates.mixins.json"